FROM eclipse-temurin:17.0.7_7-jre

ADD target/SpringBootCacheIntegrationWithRedis 0.0.1-SNAPSHOT.jar IntegrateWithPostgresSQL-0.0.1-SNAPSHOT.jar/

EXPOSE 8081

CMD java -jar SpringBootCacheIntegrationWithRedis 0.0.1-SNAPSHOT.jar