spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb_demo
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 100s


server:
  port: 8081